-- AUTO-GENERATED by gen_ctrl_lut.py — do not edit
-- Source: simulators/cyclesim/data/fsm_table.py
library ieee;
use ieee.std_logic_1164.all;

package ctrl_lut_pkg is
  type ctrl_row_t is record
    reg_we          : std_logic;
    mem_rd          : std_logic;
    mem_wr          : std_logic;
    y_oe            : std_logic;
    w_sel           : std_logic_vector(1 downto 0);
    cin             : std_logic;
    bctrl           : std_logic_vector(3 downto 0);
    lgc             : std_logic_vector(3 downto 0);
    s0              : std_logic;
    s1              : std_logic;
    pc_load_en      : std_logic;
    pc_load_flg_z   : std_logic;
    flg_we          : std_logic;
    is_xfer         : std_logic;
  end record;

  type ctrl_table_t is array (0 to 127) of ctrl_row_t;

  constant CTRL_TABLE : ctrl_table_t := (
    0 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    1 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    2 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    3 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    4 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '1', w_sel => "00",
      cin => '0', bctrl => "1100", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    5 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '1', w_sel => "01",
      cin => '0', bctrl => "1100", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    6 => (
      reg_we => '1', mem_rd => '0', mem_wr => '0',
      y_oe => '1', w_sel => "10",
      cin => '0', bctrl => "1100", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '1', is_xfer => '0'
    ),
    7 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    8 => (
      reg_we => '0', mem_rd => '1', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    9 => (
      reg_we => '1', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    10 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    11 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    12 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '1', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    13 => (
      reg_we => '0', mem_rd => '0', mem_wr => '1',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    14 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    15 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    16 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '1', bctrl => "0011", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    17 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '1', pc_load_flg_z => '1',
      flg_we => '0', is_xfer => '0'
    ),
    18 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    19 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    20 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '1', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    21 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    22 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    23 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    24 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    25 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    26 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    27 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    28 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    29 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    30 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    31 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    32 => (
      reg_we => '0', mem_rd => '1', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    33 => (
      reg_we => '1', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    34 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    35 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    36 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '1', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    37 => (
      reg_we => '0', mem_rd => '0', mem_wr => '1',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    38 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    39 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    40 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    41 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    42 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    43 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    44 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    45 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    46 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    47 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    48 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    49 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    50 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    51 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    52 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '1', w_sel => "00",
      cin => '1', bctrl => "0011", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    53 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '1', w_sel => "01",
      cin => '1', bctrl => "0011", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    54 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '1', w_sel => "00",
      cin => '1', bctrl => "0011", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '1', is_xfer => '0'
    ),
    55 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    56 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    57 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    58 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    59 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    60 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '1', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    61 => (
      reg_we => '0', mem_rd => '0', mem_wr => '1',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    62 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    63 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    64 => (
      reg_we => '1', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '1'
    ),
    65 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    66 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    67 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    68 => (
      reg_we => '1', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '1'
    ),
    69 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    70 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    71 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    72 => (
      reg_we => '1', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "01",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '1'
    ),
    73 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    74 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    75 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    76 => (
      reg_we => '1', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "01",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '1'
    ),
    77 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    78 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    79 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    80 => (
      reg_we => '1', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "10",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '1'
    ),
    81 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    82 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    83 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    84 => (
      reg_we => '1', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "10",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '1'
    ),
    85 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    86 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    87 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    88 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    89 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    90 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    91 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    92 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    93 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    94 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    95 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    96 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    97 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    98 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    99 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    100 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    101 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    102 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    103 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    104 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    105 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    106 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    107 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    108 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    109 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    110 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    111 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    112 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    113 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    114 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    115 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    116 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    117 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    118 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    119 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    120 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    121 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    122 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    123 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    124 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    125 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    126 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    ),
    127 => (
      reg_we => '0', mem_rd => '0', mem_wr => '0',
      y_oe => '0', w_sel => "00",
      cin => '0', bctrl => "0000", lgc => "0000",
      s0 => '0', s1 => '0',
      pc_load_en => '0', pc_load_flg_z => '0',
      flg_we => '0', is_xfer => '0'
    )
  );
end package ctrl_lut_pkg;

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.ctrl_lut_pkg.all;

entity ctrl_lut is
  port (
    idx5            : in  std_logic_vector(6 downto 0);
    reg_we          : out std_logic;
    mem_rd          : out std_logic;
    mem_wr          : out std_logic;
    y_oe            : out std_logic;
    w_sel           : out std_logic_vector(1 downto 0);
    cin             : out std_logic;
    bctrl           : out std_logic_vector(3 downto 0);
    lgc             : out std_logic_vector(3 downto 0);
    s0              : out std_logic;
    s1              : out std_logic;
    pc_load_en      : out std_logic;
    pc_load_flg_z   : out std_logic;
    flg_we          : out std_logic;
    is_xfer         : out std_logic
  );
end ctrl_lut;

architecture rtl of ctrl_lut is
  signal row : ctrl_row_t;
begin
  row <= CTRL_TABLE(to_integer(unsigned(idx5)));
  reg_we        <= row.reg_we;
  mem_rd        <= row.mem_rd;
  mem_wr        <= row.mem_wr;
  y_oe          <= row.y_oe;
  w_sel         <= row.w_sel;
  cin           <= row.cin;
  bctrl         <= row.bctrl;
  lgc           <= row.lgc;
  s0            <= row.s0;
  s1            <= row.s1;
  pc_load_en    <= row.pc_load_en;
  pc_load_flg_z <= row.pc_load_flg_z;
  flg_we        <= row.flg_we;
  is_xfer       <= row.is_xfer;
end rtl;
