#!/usr/bin/env python3
"""Generate ctrl_lut.vhd from simulators.cyclesim.data.fsm_table (normative)."""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from simulators.cyclesim.data.fsm_table import FSM_ROWS, Template  # noqa: E402

OUT = Path(__file__).resolve().parent / "ctrl_lut.vhd"

LUT_SLOTS = 128


def vhdl_bool(b: bool) -> str:
    return "'1'" if b else "'0'"


def vhdl_bits(n: int, width: int) -> str:
    return f'"{format(n & ((1 << width) - 1), f"0{width}b")}"'


def row_defaults() -> dict[str, str]:
    return {
        "reg_we": vhdl_bool(False),
        "mem_rd": vhdl_bool(False),
        "mem_wr": vhdl_bool(False),
        "y_oe": vhdl_bool(False),
        "w_sel": vhdl_bits(0, 2),
        "cin": vhdl_bool(False),
        "bctrl": vhdl_bits(0, 4),
        "lgc": vhdl_bits(0, 4),
        "s0": vhdl_bool(False),
        "s1": vhdl_bool(False),
        "pc_load_en": vhdl_bool(False),
        "pc_load_flg_z": vhdl_bool(False),
        "flg_we": vhdl_bool(False),
        "is_xfer": vhdl_bool(False),
    }


def emit_row(row) -> dict[str, str]:
    d = row_defaults()
    d["reg_we"] = vhdl_bool(row.reg_we)
    d["mem_rd"] = vhdl_bool(row.mem_rd)
    d["mem_wr"] = vhdl_bool(row.mem_wr)
    d["y_oe"] = vhdl_bool(row.y_oe)
    d["w_sel"] = vhdl_bits(row.w_sel, 2)
    d["cin"] = vhdl_bool(bool(row.alu.cin))
    d["bctrl"] = vhdl_bits(row.alu.bctrl, 4)
    d["lgc"] = vhdl_bits(row.alu.lgc, 4)
    d["s0"] = vhdl_bool(bool(row.alu.s0))
    d["s1"] = vhdl_bool(bool(row.alu.s1))
    d["pc_load_en"] = vhdl_bool(row.pc_load_en)
    d["pc_load_flg_z"] = vhdl_bool(row.pc_load_flg_z)
    d["flg_we"] = vhdl_bool(row.flg_we)
    d["is_xfer"] = vhdl_bool(row.template == Template.XFER)
    return d


def main() -> None:
    table = [row_defaults() for _ in range(LUT_SLOTS)]
    for row in FSM_ROWS:
        table[row.idx5] = emit_row(row)

    lines = [
        "-- AUTO-GENERATED by gen_ctrl_lut.py — do not edit",
        "-- Source: simulators/cyclesim/data/fsm_table.py",
        "library ieee;",
        "use ieee.std_logic_1164.all;",
        "",
        "package ctrl_lut_pkg is",
        "  type ctrl_row_t is record",
        "    reg_we          : std_logic;",
        "    mem_rd          : std_logic;",
        "    mem_wr          : std_logic;",
        "    y_oe            : std_logic;",
        "    w_sel           : std_logic_vector(1 downto 0);",
        "    cin             : std_logic;",
        "    bctrl           : std_logic_vector(3 downto 0);",
        "    lgc             : std_logic_vector(3 downto 0);",
        "    s0              : std_logic;",
        "    s1              : std_logic;",
        "    pc_load_en      : std_logic;",
        "    pc_load_flg_z   : std_logic;",
        "    flg_we          : std_logic;",
        "    is_xfer         : std_logic;",
        "  end record;",
        "",
        "  type ctrl_table_t is array (0 to 127) of ctrl_row_t;",
        "",
        "  constant CTRL_TABLE : ctrl_table_t := (",
    ]

    for idx in range(LUT_SLOTS):
        r = table[idx]
        comma = "," if idx < LUT_SLOTS - 1 else ""
        lines.append(f"    {idx} => (")
        lines.append(f"      reg_we => {r['reg_we']}, mem_rd => {r['mem_rd']}, mem_wr => {r['mem_wr']},")
        lines.append(f"      y_oe => {r['y_oe']}, w_sel => {r['w_sel']},")
        lines.append(f"      cin => {r['cin']}, bctrl => {r['bctrl']}, lgc => {r['lgc']},")
        lines.append(f"      s0 => {r['s0']}, s1 => {r['s1']},")
        lines.append(
            f"      pc_load_en => {r['pc_load_en']}, pc_load_flg_z => {r['pc_load_flg_z']},"
        )
        lines.append(f"      flg_we => {r['flg_we']}, is_xfer => {r['is_xfer']}")
        lines.append(f"    ){comma}")

    lines += [
        "  );",
        "end package ctrl_lut_pkg;",
        "",
        "library ieee;",
        "use ieee.std_logic_1164.all;",
        "use ieee.numeric_std.all;",
        "use work.ctrl_lut_pkg.all;",
        "",
        "entity ctrl_lut is",
        "  port (",
        "    idx5            : in  std_logic_vector(6 downto 0);",
        "    reg_we          : out std_logic;",
        "    mem_rd          : out std_logic;",
        "    mem_wr          : out std_logic;",
        "    y_oe            : out std_logic;",
        "    w_sel           : out std_logic_vector(1 downto 0);",
        "    cin             : out std_logic;",
        "    bctrl           : out std_logic_vector(3 downto 0);",
        "    lgc             : out std_logic_vector(3 downto 0);",
        "    s0              : out std_logic;",
        "    s1              : out std_logic;",
        "    pc_load_en      : out std_logic;",
        "    pc_load_flg_z   : out std_logic;",
        "    flg_we          : out std_logic;",
        "    is_xfer         : out std_logic",
        "  );",
        "end ctrl_lut;",
        "",
        "architecture rtl of ctrl_lut is",
        "  signal row : ctrl_row_t;",
        "begin",
        "  row <= CTRL_TABLE(to_integer(unsigned(idx5)));",
        "  reg_we        <= row.reg_we;",
        "  mem_rd        <= row.mem_rd;",
        "  mem_wr        <= row.mem_wr;",
        "  y_oe          <= row.y_oe;",
        "  w_sel         <= row.w_sel;",
        "  cin           <= row.cin;",
        "  bctrl         <= row.bctrl;",
        "  lgc           <= row.lgc;",
        "  s0            <= row.s0;",
        "  s1            <= row.s1;",
        "  pc_load_en    <= row.pc_load_en;",
        "  pc_load_flg_z <= row.pc_load_flg_z;",
        "  flg_we        <= row.flg_we;",
        "  is_xfer       <= row.is_xfer;",
        "end rtl;",
        "",
    ]

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT} ({len(FSM_ROWS)} active rows / {LUT_SLOTS} slots)")


if __name__ == "__main__":
    main()
