#!/usr/bin/env python3
"""Generate ctrl_lut.inc (CUPL) from simulators.cyclesim.data.fsm_table."""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from simulators.cyclesim.data.fsm_table import FSM_ROWS  # noqa: E402

OUT = Path(__file__).resolve().parent / "ctrl_lut.inc"
LUT_SLOTS = 128
MERGE_BEGIN = "/* GEN_CTRL_LUT_BEGIN */"
MERGE_END = "/* GEN_CTRL_LUT_END */"

# LUT outputs (TFR strobes come from tfr_valid comb in system_ctrl.pld)
LUT_SIGNALS = (
    "reg_we_lut",
    "mem_rd",
    "mem_wr",
    "y_oe",
    "w_sel0_lut",
    "w_sel1_lut",
    "cin",
    "bctrl0",
    "bctrl2",
    "lgc0",
    "lgc1",
    "lgc2",
    "lgc3",
    "s0",
    "s1",
    "lut_pc_load",
    "lut_pc_flg_z",
    "flg_we",
)


def idx5_pattern(idx: int) -> str:
    return format(idx & 0x7F, "07b")


def row_values(row) -> dict[str, int | bool]:
    return {
        "reg_we_lut": row.reg_we,
        "mem_rd": row.mem_rd,
        "mem_wr": row.mem_wr,
        "y_oe": row.y_oe,
        "w_sel0_lut": row.w_sel & 1,
        "w_sel1_lut": (row.w_sel >> 1) & 1,
        "cin": bool(row.alu.cin),
        "bctrl0": (row.alu.bctrl >> 0) & 1,
        "bctrl2": (row.alu.bctrl >> 2) & 1,
        "lgc0": (row.alu.lgc >> 0) & 1,
        "lgc1": (row.alu.lgc >> 1) & 1,
        "lgc2": (row.alu.lgc >> 2) & 1,
        "lgc3": (row.alu.lgc >> 3) & 1,
        "s0": bool(row.alu.s0),
        "s1": bool(row.alu.s1),
        "lut_pc_load": row.pc_load_en,
        "lut_pc_flg_z": row.pc_load_flg_z,
        "flg_we": row.flg_we,
    }


def build_table() -> list[dict[str, int | bool]]:
    table: list[dict[str, int | bool]] = [
        {k: 0 for k in LUT_SIGNALS} for _ in range(LUT_SLOTS)
    ]
    for row in FSM_ROWS:
        table[row.idx5] = row_values(row)
    return table


def cupl_or(signal: str, indices: list[int]) -> str:
    if not indices:
        return f"{signal} = 'b'0;"
    terms = [f"idx5 : 'b'{idx5_pattern(i)}" for i in indices]
    return f"{signal} = " + " # ".join(terms) + ";"


def emit_inc(table: list[dict[str, int | bool]]) -> str:
    lines = [
        "/* AUTO-GENERATED by gen_ctrl_lut.py - do not edit */",
        "/* Source: simulators/cyclesim/data/fsm_table.py */",
        "",
        "FIELD idx5 = [opc4, opc3, opc2, opc1, opc0, ph1, ph0];",
        "",
    ]
    for key in LUT_SIGNALS:
        active = [idx for idx, row in enumerate(table) if row[key]]
        lines.append(cupl_or(key, active))
    lines.append("")
    return "\n".join(lines)


def merge_into_pld(inc_text: str) -> None:
    pld = Path(__file__).resolve().parent / "system_ctrl.pld"
    if not pld.exists():
        return
    body = pld.read_text(encoding="utf-8")
    if MERGE_BEGIN not in body or MERGE_END not in body:
        return
    pre, rest = body.split(MERGE_BEGIN, 1)
    _, post = rest.split(MERGE_END, 1)
    merged = pre + MERGE_BEGIN + "\n" + inc_text + MERGE_END + post
    gen = pld.parent / "system_ctrl_gen.pld"
    gen.write_text(merged, encoding="utf-8")


def main() -> None:
    table = build_table()
    text = emit_inc(table)
    OUT.write_text(text, encoding="utf-8")
    merge_into_pld(text)
    print(f"Wrote {OUT} ({len(FSM_ROWS)} active rows / {LUT_SLOTS} slots)")


if __name__ == "__main__":
    main()
